services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: restaurant_ai_postgres
    environment:
      POSTGRES_DB: restaurant_ai
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: restaurant_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: restaurant_ai_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: